name: CRUDPipeline
on: 
  push: 
    branches: ["main"]
jobs:
  # Job 1: Build and Test (Continuous Integration)
  build-and-test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Dotnet Version
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0'

      - name: Script
        run: ls

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build

      - name: Publsih Code
        run: dotnet publish --configuration Release --no-build --output ./publish












      
