name: CRUDPipeline
on: 
  push: 
    branches: ["main"]
jobs:
  # Job 1: Build and Test (Continuous Integration)
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dotnet Version
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0'

      - name: Script
        run: pwd

      - name: Restore Dependencies
        run: dotnet restore "*.slnx"

      - name: Publsih Code
        run: dotnet publish --configuration Release --no-build --output ./publish












      
